openapi: 3.2.0
info:
  description: Sample API for Universal QR Codes
  version: 1.0.0
  title: Universal QR Code Sku API
  contact:
    email: engineering@nabis.com
tags:
- name: sku
  description: Information about sku details
paths:
  /sku/{id}:
    get:
      tags:
      - sku
      parameters:
      - in: path
        name: id
        description: id of record to look up
        required: true
        schema:
          type: string
      responses:
        '200':
          description: sku matching input identifier
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sku'
components:
  schemas:
    Sku:
      required:
      - id
      - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: Kush OG
        strain:
          type: string
      type: object
